version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task_manager_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=task_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: