// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type Task struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Status      bool   `json:"status"`
	AssignedTo  *User  `json:"assignedTo,omitempty"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type User struct {
	ID       string  `json:"id"`
	FullName string  `json:"fullName"`
	Password string  `json:"password"`
	Email    string  `json:"email"`
	Tasks    []*Task `json:"tasks"`
}
